name: PowerShell Lint and Format

on: 
  pull_request:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Format PowerShell scripts
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse -Include *.ps1
          foreach ($file in $files) {
            Write-Output "Formatting $file"
            $content = Get-Content -Path $file.FullName -Raw
            $formatted = Invoke-Formatter -ScriptDefinition $content
            Set-Content -Path $file.FullName -Value $formatted
          }

      - name: Lint PowerShell scripts
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse -Include *.ps1
          foreach ($file in $files) {
            Write-Output "Linting $file"
            Invoke-ScriptAnalyzer -Path $file.FullName -Recurse -Severity Warning,Error
          }

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes
        if: steps.git-check.outputs.changes-detected
        run: |
          git add .
          git commit -m "Formatted and linted PowerShell scripts"

      - name: Push changes
        if: steps.git-check.outputs.changes-detected
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g')
          git push origin $branch
